backlift:
  ## joint_names
  joint: backlift_body
  ## joint_state_controller
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  ## position controller
  joint_position_controller:
    type: position_controllers/JointPositionController
    joint: backlift_body
