#group:
#  group_name: <group_name>
#  component_name: <component_name>
#  buttons: [[button_name1,function_name1,parameter_name2,
#    [button_name2,function_name2,parameter_name2]]


group1:
  group_name: arm settings
  component_name: arm
  buttons: [[stop,stop],
    [init,init],
    [recover,recover],
    [halt,trigger,halt]]

group2:
  group_name: arm pos
  component_name: arm
  buttons: [[stop,stop],
    [home,move,home],
    [folded,move,folded],
    [waveleft,move,waveleft],
    [waveright,move,waveright]]

# trajectories
group3:
  group_name: arm traj
  component_name: arm
  buttons: [[stop,stop],
    [wave,move,wave]]

