neck:
  ## joint_names
  joint: head_neck
  ## joint_state_controller
  joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50
  ## position controller
  joint_position_controller:
      type: position_controllers/JointPositionController
      joint: head_neck