right_hand:
  ##joint names
  joint_names: [right_hand_knuckle_joint, right_hand_finger_12_joint, right_hand_finger_13_joint, right_hand_finger_21_joint, right_hand_finger_22_joint, right_hand_finger_23_joint, right_hand_thumb_2_joint, right_hand_thumb_3_joint]
  ## joint_state_controller
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  ## position controller
  joint_group_position_controller:
      type: position_controllers/JointGroupPositionController
      joints:
          - right_hand_knuckle_joint
          - right_hand_finger_12_joint
          - right_hand_finger_13_joint
          - right_hand_finger_21_joint
          - right_hand_finger_22_joint
          - right_hand_finger_23_joint
          - right_hand_thumb_2_joint
          - right_hand_thumb_3_joint
      required_drive_mode: 1