arm:
        ## joint_names
        joint_names: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint]
        ## joint_state_controller
        joint_state_controller:
                type: joint_state_controller/JointStateController
                publish_rate: 50
        ## position controller
        joint_group_position_controller:
                type: position_controllers/JointGroupPositionController
                joints:
                        - arm_1_joint
                        - arm_2_joint
                        - arm_3_joint
                        - arm_4_joint
                        - arm_5_joint
                        - arm_6_joint
                required_drive_mode: 1
