## joint_names
#joint_names: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint,
#left_hand_finger_21_joint, left_hand_knuckle_joint, left_hand_finger_12_joint, left_hand_finger_13_joint, left_hand_finger_22_joint.
#left_hand_finger_23_joint, left_hand_thumb_2_joint, left_hand_thumb_3_joint]
## joint_state_controller

moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_

generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01

hardware_interface:
  joints:
    - left_arm_1_joint
    - left_arm_2_joint
    - left_arm_3_joint
    - left_arm_4_joint
    - left_arm_5_joint
    - left_arm_6_joint
    - left_hand_finger_22_joint
    - left_hand_finger_23_joint
    - left_hand_knuckle_joint
    - left_hand_finger_12_joint
    - left_hand_finger_13_joint
    - left_hand_thumb_2_joint
    - left_hand_thumb_3_joint
  sim_control_mode: 1  # 0: position, 1: velocity

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
## position controller
#        left_arm_1_joint_position_controller:
#                type: position_controllers/JointPositionController
#                joint: left_arm_1_joint
#                pid: {p: 100.0, i: 0.01, d: 10.0}
left_arm_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - left_arm_1_joint
    - left_arm_2_joint
    - left_arm_3_joint
    - left_arm_4_joint
    - left_arm_5_joint
    - left_arm_6_joint
  required_drive_mode: 1
  pid: {p: 50.0, i: 0.01, d: 10.0}
left_hand_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - left_hand_finger_21_joint
    - left_hand_knuckle_joint
    - left_hand_finger_12_joint
    - left_hand_finger_13_joint
    - left_hand_finger_22_joint
    - left_hand_finger_23_joint
    - left_hand_thumb_2_joint
    - left_hand_thumb_3_joint
  required_drive_mode: 1
  pid: {p: 50.0, i: 0.01, d: 10.0}