sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /zed/zed_node/point_cloud/cloud_registered
    max_range: 5
    padding_offset: 0.01
    padding_scale: 1.0
    point_subsample: 1
    filtered_cloud_topic: output_cloud