controller_list:
  - name: fake_left_arm_controller
    joints:
      - left_arm_1_joint
      - left_arm_2_joint
      - left_arm_3_joint
      - left_arm_4_joint
      - left_arm_5_joint
      - left_arm_6_joint
  - name: fake_right_arm_controller
    joints:
      - right_arm_1_joint
      - right_arm_2_joint
      - right_arm_3_joint
      - right_arm_4_joint
      - right_arm_5_joint
      - right_arm_6_joint
  - name: fake_left_hand_controller
    joints:
      - left_hand_finger_22_joint
      - left_hand_finger_23_joint
      - left_hand_knuckle_joint
      - left_hand_finger_12_joint
      - left_hand_finger_13_joint
      - left_hand_thumb_2_joint
      - left_hand_thumb_3_joint
  - name: fake_right_hand_controller
    joints:
      - right_hand_finger_22_joint
      - right_hand_finger_23_joint
      - right_hand_knuckle_joint
      - right_hand_finger_12_joint
      - right_hand_finger_13_joint
      - right_hand_thumb_2_joint
      - right_hand_thumb_3_joint