# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - left_arm_1_joint
    - left_arm_2_joint
    - left_arm_3_joint
    - left_arm_4_joint
    - left_arm_5_joint
    - left_arm_6_joint
    - left_hand_finger_22_joint
    - left_hand_finger_23_joint
    - left_hand_knuckle_joint
    - left_hand_finger_12_joint
    - left_hand_finger_13_joint
    - left_hand_thumb_2_joint
    - left_hand_thumb_3_joint
    - right_arm_1_joint
    - right_arm_2_joint
    - right_arm_3_joint
    - right_arm_4_joint
    - right_arm_5_joint
    - right_arm_6_joint
    - right_hand_finger_22_joint
    - right_hand_finger_23_joint
    - right_hand_knuckle_joint
    - right_hand_finger_12_joint
    - right_hand_finger_13_joint
    - right_hand_thumb_2_joint
    - right_hand_thumb_3_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
left_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_arm_1_joint
    - left_arm_2_joint
    - left_arm_3_joint
    - left_arm_4_joint
    - left_arm_5_joint
    - left_arm_6_joint
  gains:
    left_arm_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_5_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_6_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - right_arm_1_joint
    - right_arm_2_joint
    - right_arm_3_joint
    - right_arm_4_joint
    - right_arm_5_joint
    - right_arm_6_joint
  gains:
    right_arm_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_5_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_6_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
left_hand_controller:
  type: position_controllers/JointPositionController
  joints:
    - left_hand_finger_22_joint
    - left_hand_finger_23_joint
    - left_hand_knuckle_joint
    - left_hand_finger_12_joint
    - left_hand_finger_13_joint
    - left_hand_thumb_2_joint
    - left_hand_thumb_3_joint
  gains:
    left_hand_finger_22_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_hand_finger_23_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_hand_knuckle_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_hand_finger_12_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_hand_finger_13_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_hand_thumb_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_hand_thumb_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_hand_controller:
  type: position_controllers/JointPositionController
  joints:
    - right_hand_finger_22_joint
    - right_hand_finger_23_joint
    - right_hand_knuckle_joint
    - right_hand_finger_12_joint
    - right_hand_finger_13_joint
    - right_hand_thumb_2_joint
    - right_hand_thumb_3_joint
  gains:
    right_hand_finger_22_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_hand_finger_23_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_hand_knuckle_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_hand_finger_12_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_hand_finger_13_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_hand_thumb_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_hand_thumb_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1